# Generated by Django 3.0.8 on 2020-07-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='руб.', verbose_name='Цена'),
        ),
    ]
