# Generated by Django 3.0.8 on 2020-07-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0002_auto_20200720_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesproduct',
            name='parent_category',
        ),
    ]
