# Generated by Django 3.0.8 on 2020-07-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0003_remove_categoriesproduct_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='without_gems',
            field=models.BooleanField(default=False, verbose_name='Без вставок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gems',
            field=models.ManyToManyField(blank=True, related_name='product_gems', to='jewelry_store.Gems', verbose_name='Драгоценные камни'),
        ),
    ]
