# Generated by Django 3.0.8 on 2020-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0004_auto_20200722_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='without_gems',
        ),
        migrations.AddField(
            model_name='product',
            name='with_gems',
            field=models.BooleanField(default=True, verbose_name='Со вставками'),
        ),
    ]
