# Generated by Django 3.0.8 on 2020-07-23 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0008_auto_20200723_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpurchases',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='руб.', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='allpurchases',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='jewelry_store.Product'),
        ),
        migrations.AlterField(
            model_name='allpurchases',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jewelry_store.Purchase'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jewelry_store.Client', verbose_name='Номер клиента'),
        ),
    ]
