# Generated by Django 3.0.8 on 2020-07-23 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0009_auto_20200723_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата изменения'),
        ),
    ]
