# Generated by Django 3.0.8 on 2020-07-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0011_auto_20200724_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpurchases',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='jewelry_store.Product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='allpurchases',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jewelry_store.Purchase', verbose_name='Заказ'),
        ),
    ]
