# Generated by Django 3.0.8 on 2020-07-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0012_auto_20200724_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='jewelry_store.Product', verbose_name='Номер продукта'),
        ),
        migrations.AlterField(
            model_name='status',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='jewelry_store.Purchase', verbose_name='Номер покупки'),
        ),
    ]
