# Generated by Django 3.0.8 on 2020-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0015_auto_20200731_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
    ]
