# Generated by Django 3.0.8 on 2020-08-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0016_auto_20200802_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
    ]
